# 排队进位时间
interval: 3

# Targert server
target: 2b2t
max-players: 300

# 玩家入队时自动在前面加入的假人
fake-players:
  prior:
    max: 1
    min: 0
  premium:
    max: 5
    min: 3
  offline:
    max: 5
    min: 3

# 优先队列过期时间戳
prior-list:
  Rabbit0w0: 0